#!/bin/bash

api-events_update() {
	conf_write status-api $1
	if [[ -a /opt/webinoly/lib/api-events ]]; then
		source /opt/webinoly/lib/api-events
		api-events_catch_status $1
	fi
}


conf_read() {
	local val=$(grep -w "^${1}:.*" /opt/webinoly/webinoly.conf | cut -f 2 -d ':')
	echo $val
}

conf_write() {
	mkdir -p /opt/webinoly
	[[ ! -a /opt/webinoly/webinoly.conf ]] && sudo touch /opt/webinoly/webinoly.conf
	#if requested VAR exists overwrite it, if not, create it.
	sed -i "/^${1}:/d" /opt/webinoly/webinoly.conf
	sh -c "echo -n '$1:$2\n' >> /opt/webinoly/webinoly.conf"
}

conf_delete() {
	sed -i "/^${1}:/d" /opt/webinoly/webinoly.conf
}



pre_install() {
	sudo apt-get -qq update
	if [[ $(conf_read pre-packs) != true ]]; then
		# Check for missing essential packages
		
		api-events_update i1
		#sudo apt-get -y -qq install software-properties-common
		#sudo apt-get -y -qq install python-software-properties
		sudo apt-get -y -qq install pwgen
		sudo apt-get -y -qq install unzip
		sudo apt-get -y -qq install zip
		conf_write pre-packs true
		api-events_update i2
		
		export DEBIAN_FRONTEND=noninteractive
		export HOSTNAME=$(curl -s http://169.254.169.254/metadata/v1/hostname)
		export PUBLIC_IPV4=$(curl -s http://169.254.169.254/metadata/v1/interfaces/public/0/ipv4/address)

		# Install Nginx
		#apt-get -y update
		#apt-get -y install nginx

		# Write hostname and IP address to index.html
		mkdir -p /var/www/html
		sed -i -e "s|/usr/share/nginx/html|/var/www/html|g" /etc/nginx/sites-available/default
		echo -e "<html><body><strong>Droplet:</strong> $HOSTNAME<br><strong>IP Address:</strong> $PUBLIC_IPV4</html></body>" \
		    > /var/www/html/index.html
	fi
}

php_install() {
	api-events_update ip1
	if [[ -n $(conf_read php-ver) && ($(conf_read php-ver) == "7.2" || $(conf_read php-ver) == "7.1" || $(conf_read php-ver) == "7.0" || $(conf_read php-ver) == "5.6") ]]; then
		echo "${gre}Default PHP version '$(conf_read php-ver)' detected!${end}"
	else
		# Default PHP version
		conf_write php-ver 7.2
	fi
	ver=$(conf_read php-ver)
	
	# Multi-PHP
	if [[ $(conf_read multi-php) == "true" && -n $1 && $1 =~ ^(5.6|7.0|7.1|7.2)$ && $(conf_read php) == "true" && $1 != $ver ]]; then
		ver="$1"
		echo "${gre}Multi-PHP version is enabled. PHP '$ver' will be installed!${end}"
	elif [[ $(conf_read multi-php) != "true" && -n $1 ]]; then
		echo "${red}Multi-PHP is not enabled! ${end}"
		exit 1
	elif [[ $(conf_read multi-php) == "true" && -n $1 ]]; then
		echo "${red}Please, enter a valid PHP version or default PHP is not installed yet! ${end}"
		exit 1
	fi
	
	if [[ $(conf_read php) != "true" ]]; then
		# Fix ondrej issue - https://github.com/oerdnj/deb.sury.org/issues/56
		sudo apt-get install -y language-pack-en-base
		sudo LC_ALL=C.UTF-8 add-apt-repository -y ppa:ondrej/php
	fi
	pre_install
	sudo apt-get -y install php${ver}-common php${ver}-cli php${ver}-fpm php${ver}-curl php${ver}-gd php${ver}-imap php${ver}-readline php${ver}-recode php${ver}-mysql php${ver}-mbstring php${ver}-bcmath php${ver}-mysql php${ver}-opcache php${ver}-zip php${ver}-xml php${ver}-soap php-imagick graphviz php-pear php-msgpack
	
	if [[ -n $ver && ($ver == "7.1" || $ver == "7.0" || $ver == "5.6") ]]; then
		# mcrypt deprecated in 7.2
		sudo apt-get -y install php${ver}-mcrypt
	fi
	if [[ -n $ver && ($ver == "7.2" || $ver == "7.1" || $ver == "7.0") ]]; then
		# xdebug deprecated in 5.6
		sudo apt-get -y install php-xdebug
	fi
	
	def=$(conf_read php-ver)
	if [[ $(conf_read php-v${def}) != "true" ]]; then
		sudo cp /etc/php/$ver/fpm/php.ini /opt/webinoly/templates/source/
		sudo cp /etc/php/$ver/fpm/pool.d/www.conf /opt/webinoly/templates/source/
	fi
	
	conf_write php true
	conf_write php-v$ver true
	echo "${gre}PHP has been installed successfully! ${end}"
	api-events_update ip2
}


mysql_install() {
	api-events_update im1
	[[ $(conf_read mysql-client) != "true" ]] && mysql_client_install
	
	pre_install
	# debconf-utils for unattended scripts
	#  debconf-get-selections | grep phpmyadmin   <<-- list conf variables
	sudo apt-get -y install debconf-utils
	
	# Generate mysql user passwords
	local AUTOGENPASS_ROOT=`pwgen -s -1`
	local AUTOGENPASS_ADMIN=`pwgen -s -1`
	local enc_pass_root=$( echo $AUTOGENPASS_ROOT | openssl enc -a -salt )
	local enc_pass_admin=$( echo $AUTOGENPASS_ADMIN | openssl enc -a -salt )
	conf_write mysql-root $enc_pass_root
	conf_write mysql-admin $enc_pass_admin
	
	# MariaDB Installation
	echo "mariadb-server-10.2 mysql-server/root_password password $AUTOGENPASS_ROOT" | debconf-set-selections
	echo "mariadb-server-10.2 mysql-server/root_password_again password $AUTOGENPASS_ROOT" | debconf-set-selections
	sudo apt-get -y install mariadb-server

	#Instead of mysql_secure_installation we do this: (same but manually, because not acept unattended)
	#ALTER USER 'root'@'localhost' IDENTIFIED BY '${AUTOGENPASS_ROOT}';   <<<--- For MySQL 5.7.6 and newer as well as MariaDB 10.1.20 and newer instead of UPDATE
	sudo mysql --user=root -p$AUTOGENPASS_ROOT <<_EOF_
UPDATE mysql.user SET authentication_string = PASSWORD('${AUTOGENPASS_ROOT}') WHERE User = 'root' AND Host = 'localhost';
DELETE FROM mysql.user WHERE User='';
DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
DROP DATABASE IF EXISTS test;
DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
CREATE USER IF NOT EXISTS 'admin'@'localhost' IDENTIFIED BY '${AUTOGENPASS_ADMIN}';
GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;
_EOF_

	conf_write mysql true
	echo "${gre}MySQL has been installed successfully! ${end}"
	api-events_update im4
}

mysql_install
php_install
